### ISSUE TITLE
New exception

### ISSUE THREAD

**Issue by marco44** [matthewtckr/pdi-zendesk-plugin#38]
Hi,

I just started having this exception:
```
java.lang.NullPointerException
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
        at java.text.DateFormat.parse(DateFormat.java:364)
        at org.pentaho.di.trans.steps.zendesk.ZendeskTicketAuditHistory.processEvents(ZendeskTicketAuditHistory.java:215)
        at org.pentaho.di.trans.steps.zendesk.ZendeskTicketAuditHistory.createNextAudit(ZendeskTicketAuditHistory.java:117)
        at org.pentaho.di.trans.steps.zendesk.ZendeskInputTicketAuditData.addAudit(ZendeskInputTicketAuditData.java:61)
        at org.pentaho.di.trans.steps.zendesk.ZendeskInputTicketAudit.processRow(ZendeskInputTicketAudit.java:119)
        at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
        at java.lang.Thread.run(Thread.java:748)
```

From looking at the code, it seems that this is where it fails:

```
this.dueAt = DUE_AT_DATE_FORMAT.parse( fieldValue );
```

This is declared as

```
  private static final String DUE_AT_DATE_FORMAT_STRING = "yyyy-MM-dd HH:mm:ss";
  private static final SimpleDateFormat DUE_AT_DATE_FORMAT = new SimpleDateFormat( DUE_AT_DATE_FORMAT_STRING );
```

It probably means that the string hasn't this format ? But how can I extract this string and see what comes in to debug this ?

Regards

**Comment by marco44** [comment]
Mmm, I juste realized that this piece of code has a try catch, but this is a null pointer exception, not a parse exception… it means fieldvalue is null, right ?

**Comment by matthewtckr** [comment]
Yes, that looks like the issue to me.  I'll push something up today for this.

**Comment by marco44** [comment]
I'm trying a simple if(fieldValue != null) for now…

**Comment by matthewtckr** [comment]
Created #39 to address this

**Comment by marco44** [comment]
Yes, the patch will work, I managed to run the import with almost the same code

**Comment by marco44** [comment]
Ok, I applied the patch to my system, and managed to do the import. Thanks a lot !

**Comment by matthewtckr** [comment]
Committed #39
